[workspace]
resolver = "3"
members = ["Error-Reboot", "game", "marco"]
default-members = ["Error-Reboot"]
[workspace.package]
version = "0.0.1"
edition = "2024"
description = "Error: Reboot"
publish = false
[workspace.dependencies]
game = { path = "game" }
marco = { path = "marco" }
