name: release
on: [ push, pull_request ]
jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: x86_64-linux.tar.gz
          - platform: macos-latest
            target: x86_64-apple-darwin
            suffix: x86_64-macos.tar.gz
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: x86_64-windows.7z
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy, test

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}[1](@ref)

      - name: Cache APT packages
        if: matrix.platform == 'ubuntu-latest'
        id: cache-apt
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives  # APT下载的包缓存路径
          key: ${{ runner.os }}-apt-${{ hashFiles('**/dependencies.hash') }}  # 依赖文件哈希
          restore-keys: |
            ${{ runner.os }}-apt
      - name: Generate dependencies hash
        if: matrix.platform == 'ubuntu-latest' && steps.cache-apt.outputs.cache-hit != 'true'
        run: |
          echo "libasound2-dev alsa-utils" > dependencies.list
          sha256sum dependencies.list > dependencies.hash

      - name: Install ALSA libraries
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libasound2-dev alsa-utils

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target ${{ matrix.target }}

      - uses: actions-rs/cargo@v1
        with:
          command: test --target ${{ matrix.target }}

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy --target ${{ matrix.target }}

      - name: Run fmt check
        run: cargo fmt --target ${{ matrix.target }} -- --check

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: target/${{ matrix.target }}/release/
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/*
